"""Initial schema setup

Revision ID: 40a5e085e6cc
Revises: 
Create Date: 2026-03-07 21:16:16.142067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '40a5e085e6cc'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goals',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('horizon', sa.Enum('immediate', 'short_term', 'long_term', name='goalhorizon'), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', 'abandoned', name='goalstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interactions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('response', sa.Text(), nullable=True),
    sa.Column('intent', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('memories_written', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=True),
    sa.Column('memories_retrieved', postgresql.ARRAY(sa.UUID()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('memory_type', sa.Enum('episodic', 'semantic', 'procedural', name='memorytype'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('compressed_content', sa.Text(), nullable=True),
    sa.Column('embedding', Vector(1536), nullable=True),
    sa.Column('strength', sa.Float(), nullable=False),
    sa.Column('reinforcement_count', sa.Integer(), nullable=False),
    sa.Column('half_life_hours', sa.Float(), nullable=False),
    sa.Column('last_accessed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('decay_state', sa.Enum('active', 'fading', 'dormant', 'archived', name='decaystate'), nullable=False),
    sa.Column('trust_score', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('user_stated', 'user_repeated', 'system_inferred', 'consolidated', name='sourcetype'), nullable=False),
    sa.Column('salience', sa.Float(), nullable=False),
    sa.Column('context_tags', postgresql.ARRAY(sa.Text()), server_default='{}', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('memory_edges',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('from_memory_id', sa.UUID(), nullable=False),
    sa.Column('to_memory_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.Enum('temporal', 'causal', 'contradicts', 'consolidates', 'associated', name='edgetype'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_memory_id'], ['memories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_memory_id'], ['memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('memory_edges')
    op.drop_table('memories')
    op.drop_table('interactions')
    op.drop_table('goals')
    # ### end Alembic commands ###
