"""Add reconsolidation log and enums

Revision ID: f4f2d4e3c61b
Revises: 40a5e085e6cc
Create Date: 2026-03-22 00:44:09.828276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4f2d4e3c61b'
down_revision: Union[str, Sequence[str], None] = '40a5e085e6cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconsolidation_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('memory_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('original_content', sa.Text(), nullable=False),
    sa.Column('updated_content', sa.Text(), nullable=True),
    sa.Column('trust_before', sa.Float(), nullable=False),
    sa.Column('trust_after', sa.Float(), nullable=False),
    sa.Column('trigger_message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['memory_id'], ['memories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reconsolidation_log')
    # ### end Alembic commands ###
